#!/bin/sh
# A script to install the Fusion Directory Netatalk plugin and required
# software.
# FIXME: This script is incomplete, probably incorrect and not working.

# We must run this script as root
if [ "$USER" != "root" ]; then
        echo "Must be root to execute script..."
        exit 1
fi

# FIXME: prerequisite scripts (we should test these have run :
# squeeze-install-FusionDirectory
if [ ! -f /etc/fusiondirectory/fusiondirectory.conf ]; then
  echo "Run the squeeze-install-FusionDirectory script before this one.  fusiondirectory must be"
  echo "installed and configured before we can continue..."
  exit 1
fi

# Netatalk requires a valid network IP...
my_fqdn=`hostname -f`
my_host_ip=`grep $my_fqdn /etc/hosts | awk '{ print $1 }'`
echo ""
echo "Your hostname is "$my_fqdn" and your IP is "$my_host_ip
if [ "$my_host_ip" = "127.0.1.1" ] || [ "$my_host_ip" = "127.0.0.1" ]; then
	echo ""
	echo "Netatalk requires your hostname to resolve to a valid network IP."
	echo "You must edit your /etc/hosts file and make sure your hostname"
	echo "(printed above) resolves to an IP other than 127.x.x.x"
	echo "Your /etc/networking/interfaces will also need to match. eg. :"
	echo "iface eth0 inet static"
	echo "    address 192.168.1.120"
	echo "    netmask 255.255.255.0"
	echo "    gateway 192.168.1.1" 
	exit 1
fi

aptitude install -y --allow-untrusted netatalk fusiondirectory-plugin-netatalk

# FIXME: Apparently fusiondirectory-plugin-goto is required for the Network Share service.
#        BUT for basic auth support we probably don't need it...  but in this case should
#        we bother to install the netatalk plugin?  Investigate.
# FIXME: Apparently Netatalk authenticates via PAM, so we need to set up PAM
#        LDAP authentication perhaps at the Linux level.  I've done this
#        already in the Samba script, so perhaps that method could be cut
#        and pasted here.  Both scripts would need to check if modifications
#        have been done by the other in this case.

# FIXME: Until GOsa 2.6.11-2 (and trigger support) update-fusiondirectory needs
#        to be run manually.  update-fusiondirectory updates the interface
#        after new plugins are installed.
update-fusiondirectory

echo ""
# FIXME: Is the following explanation accurate and complete???
echo "In System management you must edit a server and add a service"
echo "of type 'File service (Shares)'.  You can then configure"
echo "this service to make available Netatalk shares."
echo "Then to edit a users Netatalk settings go to the 'Netatalk' tab in User"
echo "administration."
