#!/bin/bash
# Shell script to install Argonaut (Server Infrastructure daemon)
# FIXME: Appears to work but is VERY new.  Extreme caution!
if [ "$USER" != "root" ]; then
        echo "Must be root to execute script..."
        exit 1
fi

# FIXME: Right now argonaut is beta so we add a temporary beta repo. remove later
echo "deb http://repos.fusiondirectory.org/argonaut-beta/ ./" >> /etc/apt/sources.list.d/fusiondirectory.list

echo "Downloading package lists...  This may take a while..."
if apt-get -qq update; then
        echo "Success"
else
        echo "Failure to download package information.  Exiting..."
        exit 1
fi

# FIXME: prerequisite scripts (we should test these have run :
# squeeze-install-FusionDirectory
if [ ! -f /etc/fusiondirectory/fusiondirectory.conf ]; then
  echo "Run the squeeze-install-FusionDirectory script before this one.  Fusion"
  echo "Directory must be installed and configured before we can continue..."
  exit 1
fi

# NOTE:: We install argonaut-client as well as the server because both 
# Fusion Directory and the infrastructure we're controlling are on the one box.

apt-get -y --allow-unauthenticated install argonaut-client-management argonaut-server argonaut-common 

# Argonaut needs to be configured. :

# We raid Fusion Directory's config file, and examine our network config for
# values we need to configure Argonaut :
LDAP_ADMIN_DN=`grep 'adminDn="' /etc/fusiondirectory/fusiondirectory.conf | awk -F'"' '{ print $2 }' #| awk -F',' '{ print $1 }'`
echo "LDAP admin dn extracted from /etc/fusiondirectory/fusiondirectory.conf"
# FIXME: We no longer need to extract the base DN, but I'm keeping this around in case this changes.
#LDAP_BASE_DN=`ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=config olcSuffix | grep ^olcSuffix | awk '/ */{ print $2 }'`
#echo "Base DN extracted from slapd.d configuration : "$LDAP_BASE_DN
LDAP_ADMIN_PW=`grep 'adminPassword="' /etc/fusiondirectory/fusiondirectory.conf | awk -F'"' '{print $2 }'`
echo "LDAP admin password extracted from /etc/fusiondirectory/fusiondirectory.conf"
FQDN=`hostname --fqdn`
HOST_IP=`hostname --ip`
HOST_INTERFACE=`ifconfig | awk '/^[a-z]/ { I=$1}; /'$HOST_IP'/ {print(I)}'`

# We plug the above values into argonauts config...
sed -i 's@127.0.0.1@'$HOST_IP'@' /etc/argonaut/argonaut.conf
sed -i 's@eth0@'$HOST_INTERFACE'@' /etc/argonaut/argonaut.conf
sed -i 's@secret@'$LDAP_ADMIN_PW'@' /etc/argonaut/argonaut.conf
sed -i 's@cn=admin,dc=fusiondirectory,dc=org@'$LDAP_ADMIN_DN'@' /etc/argonaut/argonaut.conf

# ...and allow Fusion Directory to know about our argonaut server.
sed -i 's@<location name=.*$'\
'@&\n'\
'              argonautServer="http://'$HOST_IP':8080"@' /etc/fusiondirectory/fusiondirectory.conf

# Enable argonaut daemon
sed -i 's@START_SERVER=0@START_SERVER=1@' /etc/default/argonaut-server

# We need to restart the argonaut daemon.  
/etc/init.d/argonaut-server stop
/etc/init.d/argonaut-server start
/etc/init.d/argonaut-client-management stop
/etc/init.d/argonaut-client-management start

# FIXME: I THINK the argonaut-client-management server still isn't working yet, so run it manually
/usr/sbin/argonaut-client-management &
