#!/bin/bash
# Shell script to install Argonaut (Server Infrastructure daemon)
# FIXME: Appears to work but is VERY new.  Extreme caution!
if [ "$USER" != "root" ]; then
        echo "Must be root to execute script..."
        exit 1
fi

# Download and install signing keys for FD packages.
apt-get update
apt-get install wget
wget -O - http://repos.fusiondirectory.org/gpg/fusiondirectory_public.key | apt-key add -

########
# FIXME: Right now argonaut is beta so we add a temporary beta repo. remove later
REPO_CHOICE=0
while [ $REPO_CHOICE -lt 1 ] || [ $REPO_CHOICE -gt 2 ]
do
  echo ""
  echo "Which Argonaut repository will you be using? :"
  echo "1) A local Argonaut repo (manually run argonaut-nightly.sh first!!!)"
  echo "2) Benoits beta repo (can be out of date sometimes)"
#  echo "3) ...a third choice..."
  echo ""
  echo "...enter the number of your choice :"
  read REPO_CHOICE

  if [ $REPO_CHOICE -eq 1 ]; then
    if [ ! -f /etc/apt/sources.list.d/argonaut.list ]; then
      echo "deb http://`hostname --fqdn`/argonaut-beta/ squeeze main" > /etc/apt/sources.list.d/argonaut.list
    fi
  fi

  if [ $REPO_CHOICE -eq 2 ]; then
    if [ ! -f /etc/apt/sources.list.d/argonaut.list ]; then
      echo "deb http://repos.fusiondirectory.org/argonaut-libs/ squeeze main" > /etc/apt/sources.list.d/argonaut.list
      echo "deb http://repos.fusiondirectory.org/argonaut-develop/ squeeze main" >> /etc/apt/sources.list.d/argonaut.list
    fi
  fi
done
########

echo "Downloading package lists...  This may take a while..."
if apt-get -qq update; then
        echo "Success"
else
        echo "Failure to download package information.  Exiting..."
        exit 1
fi

# FIXME: prerequisite scripts (we should test these have run :
# squeeze-install-FusionDirectory
if [ ! -f /etc/fusiondirectory/fusiondirectory.conf ]; then
  echo "Run the squeeze-install-FusionDirectory script before this one.  Fusion"
  echo "Directory must be installed and configured before we can continue..."
  exit 1
fi

# NOTE:: We install argonaut-client as well as the server because both 
# Fusion Directory and the infrastructure we're controlling are on the one box.

if apt-get -y --allow-unauthenticated install fusiondirectory-plugin-argonaut fusiondirectory-plugin-argonaut-schema fusiondirectory-plugin-systems fusiondirectory-plugin-systems-schema argonaut-server argonaut-client argonaut-common fusiondirectory-plugin-asterisk-schema; then
	echo "Installation of Argonaut and prerequisite packages successful..."
else
	echo "Installation of Argonaut and prerequisite packages failed.  Exiting..."
	exit 1
fi 

# Add LDAP schemas to our directory
fusiondirectory-insert-schema -i /etc/ldap/schema/fusiondirectory/asterisk-fd.schema  /etc/ldap/schema/fusiondirectory/systems-fd-conf.schema /etc/ldap/schema/fusiondirectory/service-fd.schema /etc/ldap/schema/fusiondirectory/argonaut-fd.schema

# We raid Fusion Directory's config file, and examine our network config for
# values we need to configure Argonaut :
LDAP_ADMIN_DN=`grep 'adminDn="' /etc/fusiondirectory/fusiondirectory.conf | awk -F'"' '{ print $2 }' #| awk -F',' '{ print $1 }'`
echo "LDAP admin dn extracted from /etc/fusiondirectory/fusiondirectory.conf"
# FIXME: We no longer need to extract the base DN, but I'm keeping this around in case this changes.
#LDAP_BASE_DN=`ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=config olcSuffix | grep ^olcSuffix | awk '/ */{ print $2 }'`
#echo "Base DN extracted from slapd.d configuration : "$LDAP_BASE_DN
LDAP_ADMIN_PW=`grep 'adminPassword="' /etc/fusiondirectory/fusiondirectory.conf | awk -F'"' '{print $2 }'`
echo "LDAP admin password extracted from /etc/fusiondirectory/fusiondirectory.conf"
FQDN=`hostname --fqdn`
HOST_IP=`hostname --ip`
HOST_INTERFACE=`ifconfig | awk '/^[a-z]/ { I=$1}; /'$HOST_IP'/ {print(I)}'`

# We plug the above values into argonauts config...
sed -i 's@127.0.0.1@'$HOST_IP'@' /etc/argonaut/argonaut.conf
sed -i 's@eth0@'$HOST_INTERFACE'@' /etc/argonaut/argonaut.conf
sed -i 's@secret@'$LDAP_ADMIN_PW'@' /etc/argonaut/argonaut.conf
sed -i 's@cn=admin,dc=fusiondirectory,dc=org@'$LDAP_ADMIN_DN'@' /etc/argonaut/argonaut.conf

# ...and allow Fusion Directory to know about our argonaut server.
sed -i 's@<location name=.*$'\
'@&\n'\
'              argonautServer="http://'$HOST_IP':8080"@' /etc/fusiondirectory/fusiondirectory.conf

# Enable argonaut daemon
sed -i 's@START_SERVER=0@START_SERVER=1@' /etc/default/argonaut-server
sed -i 's@START_CLIENT=0@START_CLIENT=1@' /etc/default/argonaut-client

echo ""
echo "You must :"
echo "  * add an Argonaut server object to LDAP."
echo "  * enable the Argonaut Client functionality (in the tab of this name"
#FIXME: Make better wording, and understand better.
echo "< WHEN FINISHED hit enter to continue... >"
read my_dummy_value

# We need to restart the argonaut daemon.  
/etc/init.d/argonaut-server stop
/etc/init.d/argonaut-server start
/etc/init.d/argonaut-client stop
/etc/init.d/argonaut-client start

