#!/bin/bash
# We must run this script as root
if [ "$USER" != "root" ]; then
        echo "Must be root to execute script..."
        exit 1
fi

if [ "$my_host_ip" = "127.0.1.1" ] || [ "$my_host_ip" = "127.0.0.1" ]; then
	echo ""
	echo "You should really make your hostname resolve to a valid network IP."
	echo "This is required for plugins such as OPSI and is generally a good idea."
	echo "To do this:"
	echo "1) edit your /etc/hosts file and make sure your hostname"
	echo "   resolves to an IP other than 127.x.x.x"
	echo "2) Your /etc/network/interfaces will need to match. eg. :"
	echo "   iface eth0 inet static"
	echo "     address 192.168.1.120"
	echo "     netmask 255.255.255.0"
	echo "     gateway 192.168.1.1"
	echo "To make this take effect : killall dhclient;ifdown eth0;ifup eth0"
	echo "'Ctrl-C' to exit or hit <enter> to continue..."
	read my_dummy_value 
fi

apt-get -y install postgresql

echo ""
echo "!!!NOTE!!!"
echo "The next few steps are slow, but can be speeded up in a couple of ways."
echo "Encryption needs random numbers to be generated, and Linux normally generates"
echo "these by gathering entropy from disk accesses, keyboard and mouse use etc..."
echo "Artifically creating more local disk/mouse/keyboard usage therefore speeds"
echo "things.  You can also use pseudorandom numbers, but this is a security risk."
echo "!!!WARNING!!! Executing the following commands does this:"
echo "apt-get -y install rng-utils"
echo "rngd -r /dev/urandom"
echo "<hit enter to continue>"
read DUMMY
apt-get -y install prelude-manager prelude-lml prelude-correlator samhain

apt-get install -y logcheck syslog-summary harden harden-clients harden-environment harden-servers checksecurity harden-tools auditd audispd-plugins

sed -i 's@^\[Log\]@\[Log\]\
  PreludeSeverity=crit\
  PreludeClass=EVENT@' /etc/samhain/samhainrc
sed -i 's@^\[Misc\]@\[Misc\]\
  PreludeProfile=samhain@' /etc/samhain/samhainrc

sed -i 's@^active = no@active = yes\
q_depth = 1024\
priority_boost = 12\
name_format = NUMERIC@' /etc/audisp/plugins.d/au-prelude.conf
sed -i 's@# node-name = Name of the equipment@node-name = '`hostname --fqdn`'@' /etc/prelude/default/global.conf
sed -i 's@priority_boost = 4@priority_boost = 5@' /etc/audit/auditd.conf
sed -i 's@disp_qos = lossy@disp_qos = lossless@' /etc/audit/auditd.conf
/etc/init.d/auditd restart

sed -i 's@RUN=no@RUN=yes@' /etc/default/prelude-manager
sed -i 's@RUN=no@RUN=yes@' /etc/default/prelude-correlator

/etc/init.d/prelude-manager start

# FIXME: Security risk, but a small one.  This one-time password will be visible in the
#        clear to 'ps -aux' for a short time to local users.
PRELUDE_PW=`openssl rand -base64 30|tr -dc _A-Z-a-z-0-9`

apt-get -y install snort

sed -i 's@# output alert_prelude@output alert_prelude@' /etc/snort/snort.conf

#snort
prelude-admin registration-server prelude-manager --passwd $PRELUDE_PW --no-confirm &
prelude-admin register "snort" "idmef:w" 127.0.0.1 --uid snort --gid snort --passwd $PRELUDE_PW

/etc/init.d/snort restart

#prelude-lml
prelude-admin registration-server prelude-manager --passwd $PRELUDE_PW --no-confirm &
prelude-admin register "prelude-lml" "idmef:w" 127.0.0.1 --uid root --gid root --passwd $PRELUDE_PW

#prelude-correlator
prelude-admin registration-server prelude-manager --passwd $PRELUDE_PW --no-confirm &
prelude-admin register "prelude-correlator" "idmef:rw" 127.0.0.1 --uid prelude-correlator --gid prelude-correlator --passwd $PRELUDE_PW

#samhain
prelude-admin registration-server prelude-manager --passwd $PRELUDE_PW --no-confirm &
prelude-admin register "samhain" "idmef:w" 127.0.0.1 --uid 0 --gid 0 --passwd $PRELUDE_PW

# FIXME: For some reason the auditd plugin doesn't work unless I manually run
#        audisp-prelude.  Is this a bug?  Am I doing something wrong??

##auditd
#apt-get install auditd
#prelude-admin registration-server prelude-manager --passwd $PRELUDE_PW --no-confirm &
#prelude-admin register "auditd" "idmef:w" 127.0.0.1 --uid 0 --gid 0 --passwd $PRELUDE_PW

apt-get -y install prewikka libapache2-mod-python
# FIXME: configure mod python instead of CGI here?

echo ""
echo "You need to reenter the prelude database password (required for web GUI):"
echo "<please enter the password, then press enter...>"
read USER_PW

sed -i 's@type: mysql@type: pgsql@' /etc/prewikka/prewikka.conf
sed -i 's@pass: prelude@pass: '$USER_PW'@' /etc/prewikka/prewikka.conf

/etc/init.d/prelude-correlator start
/etc/init.d/prelude-lml start
/etc/init.d/auditd restart

MY_HOSTNAME=`hostname --fqdn`
cat > /etc/apache2/sites-available/prewikka <<-EOF
Alias /prelude/prewikka /usr/share/prewikka/htdocs/
Setenv PREWIKKA_CONFIG "/etc/prewikka/prewikka.conf"
ScriptAlias /prelude/ /usr/share/prewikka/cgi-bin/prewikka.cgi
<Directory "/usr/share/prewikka/htdocs/">
        AllowOverride None
        Options ExecCGI

        <IfModule mod_mime.c>
                AddHandler cgi-script .cgi
        </IfModule>

        Order allow,deny
        Allow from all
</Directory>
EOF

chgrp www-data /etc/prewikka/prewikka.conf

a2enmod python
a2ensite prewikka
service apache2 reload

echo "The path to your Prelude web interface can be accessed from the following URL:"
echo "https://"`hostname --fqdn`"/prelude/"
echo "!!!CHANGE THE ADMIN PASSWORD!!!"
